name: BuildAndDeploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    
    - name: build
      uses: jakejarvis/hugo-build-action@v0.86.0  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --buildDrafts

    - name: deploy-website
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./public/
